### ISSUE TITLE
关于TFlite在K210上支持的问题

### ISSUE THREAD

**Issue by DUXin-ece** [QingChuanWS/TensorflowLiteMicro#2]
您好，看到您在TODO中写到下一步会测试在K210上TFLite的运行情况。想问一下，目前TensorFlow Lite是运行在K210的CPU上还是NPU上？

**Comment by QingChuanWS** [comment]
目前K210的Tflitemicro还是放在CPU上跑, 下一步的计划就是针对K210的NPU提供一些算子来支持某些模型在NPU上计算的. 如果有意向对K210平台进行优化的话可以邮箱联系我, 咱们进一步沟通

**Comment by DUXin-ece** [comment]
好的. 目前我们想做一些这方面的工作,如果有进展的话我邮件联系您
